name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
            fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
      - name: Build
        run: hugo --minify
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: master
          FOLDER: public
